# Generated by Django 4.2.3 on 2023-07-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='recipient',
            new_name='RecId',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='sender',
            new_name='senderId',
        ),
    ]
